spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true

# desabilita a leitura automática do data.sql
spring.sql.init.mode=never

# Show SQL queries
# spring.jpa.show-sql=true

# Format SQL for readability
# spring.jpa.properties.hibernate.format_sql=true

# Show SQL parameter binding
# spring.jpa.properties.hibernate.use_sql_comments=true

# Set logging level for Hibernate
# logging.level.org.hibernate.SQL=DEBUG
# logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE